// Date: 12/16/2012 7:50:14 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package mods.atomiccraft.core.proxy;

import cpw.mods.fml.common.Side;
import cpw.mods.fml.common.asm.SideOnly;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

@SideOnly(Side.CLIENT)
public class ModelSplitter extends ModelBase
{
  //fields
    ModelRenderer Top;
    ModelRenderer Front;
    ModelRenderer Back;
    ModelRenderer Bottom;
    ModelRenderer Inside;
    ModelRenderer BottomPeg;
    ModelRenderer TopPeg;
    ModelRenderer Left;
    ModelRenderer Right;
  
  public ModelSplitter()
  {
    textureWidth = 512;
    textureHeight = 512;
    
      Top = new ModelRenderer(this, 0, 32);
      Top.addBox(0F, 0F, 0F, 16, 0, 16);
      Top.setRotationPoint(-8F, 8.1F, -8F);
      Top.setTextureSize(512, 512);
      Top.mirror = true;
      setRotation(Top, 0F, 0F, 0F);
      Front = new ModelRenderer(this, 32, 0);
      Front.addBox(0F, 0F, 0F, 16, 16, 0);
      Front.setRotationPoint(-8F, 8F, -7.9F);
      Front.setTextureSize(512, 512);
      Front.mirror = true;
      setRotation(Front, 0F, 0F, 0F);
      Back = new ModelRenderer(this, 72, 0);
      Back.addBox(0F, 0F, 0F, 16, 16, 0);
      Back.setRotationPoint(-8F, 8F, 7.9F);
      Back.setTextureSize(512, 512);
      Back.mirror = true;
      setRotation(Back, 0F, 0F, 0F);
      Bottom = new ModelRenderer(this, 72, 72);
      Bottom.addBox(0F, 0F, 0F, 16, 0, 16);
      Bottom.setRotationPoint(-8F, 23.99F, -8F);
      Bottom.setTextureSize(512, 512);
      Bottom.mirror = true;
      setRotation(Bottom, 0F, 0F, 0F);
      Inside = new ModelRenderer(this, 120, 0);
      Inside.addBox(0F, 0F, 0F, 4, 4, 4);
      Inside.setRotationPoint(-2F, 14F, -2F);
      Inside.setTextureSize(512, 512);
      Inside.mirror = true;
      setRotation(Inside, 0F, 0F, 0F);
      BottomPeg = new ModelRenderer(this, 120, 120);
      BottomPeg.addBox(0F, 0F, 0F, 2, 6, 2);
      BottomPeg.setRotationPoint(-1F, 17.9F, -1F);
      BottomPeg.setTextureSize(512, 512);
      BottomPeg.mirror = true;
      setRotation(BottomPeg, 0F, 0F, 0F);
      TopPeg = new ModelRenderer(this, 130, 130);
      TopPeg.addBox(0F, 0F, 0F, 2, 6, 2);
      TopPeg.setRotationPoint(-1F, 8.2F, -1F);
      TopPeg.setTextureSize(512, 512);
      TopPeg.mirror = true;
      setRotation(TopPeg, 0F, 0F, 0F);
      Left = new ModelRenderer(this, 100, 32);
      Left.addBox(0F, 0F, 0F, 0, 16, 16);
      Left.setRotationPoint(-7.9F, 8F, -8F);
      Left.setTextureSize(512, 512);
      Left.mirror = true;
      setRotation(Left, 0F, 0F, 0F);
      Right = new ModelRenderer(this, 0, 72);
      Right.addBox(0F, 0F, 0F, 0, 16, 16);
      Right.setRotationPoint(7.9F, 8F, -8F);
      Right.setTextureSize(512, 512);
      Right.mirror = true;
      setRotation(Right, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Top.render(f5);
    Front.render(f5);
    Back.render(f5);
    Bottom.render(f5);
    Inside.render(f5);
    BottomPeg.render(f5);
    TopPeg.render(f5);
    Left.render(f5);
    Right.render(f5);
  }
  
  public void render(float f5){
  Top.render(f5);
  Front.render(f5);
  Back.render(f5);
  Bottom.render(f5);
  Inside.render(f5);
  BottomPeg.render(f5);
  TopPeg.render(f5);
  Left.render(f5);
  Right.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity f6)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, f6);
  }


}
